name: Continuous Integration

on: [push, pull_request]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up python
          uses: actions/setup-python@v3
          with:
            python-version: "3.12"
        - name: Install uv
          run: pip install uv
        - name: Install dependancies
          run: uv sync --all-extras
        - name: Test
          run: uv run pytest
        - name: Lint with ruff
          run: uv run ruff check
        - name: Format
          run: uv run ruff format
        - name: Run type checker
          run: uv run ty check .




